### ISSUE TITLE
Cannot run a basic project

### ISSUE THREAD

**Issue by Traderain** [pgourlain/vscode_erlang#173]
Hey,
I am trying to run the program with a basic hello world example but I cannot get the extension to run output:
hf.erl:
```erl
% hello world program
-module(helloworld).
-export([start/0]).

start() ->
    io:fwrite("Hello, world!\n").
```
Launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run erlang program",
            "type": "erlang",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "preLaunchTask": "rebar3 compile"
        }
    ]
}
```
Tasks.json:
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "rebar3 compile",
            "type": "shell",
            "command": "rebar3 compile",
            "group": {
                "kind" :"build",
                "isDefault": true
            },
            "problemMatcher": "$erlang"
        }
    ]
}
```
I have installed erlang and rebar with chocolatey: 
```bash
choco install rebar3
```
![image](https://user-images.githubusercontent.com/6411732/95105552-99364b00-0737-11eb-877d-1a57dc0dcdf0.png)

Error:
```log
Error: ENOENT: no such file or directory, scandir 'D:\Repos\BME\7_Felev\Dekla\erlang\_build' at Object.readdirSync (fs.js:854:3) at Object.fs.readdirSync (electron/js2c/asar.js:621:39) at ErlangShellForDebugging.findEbinDirs (c:\Users\hamba\.vscode\extensions\pgourlain.erlang-0.6.5\out\lib\ErlangShellDebugger.js:86:12) at ErlangShellForDebugging.createArgsFilev1 (c:\Users\hamba\.vscode\extensions\pgourlain.erlang-0.6.5\out\lib\ErlangShellDebugger.js:154:22) at ErlangShellForDebugging.Start (c:\Users\hamba\.vscode\extensions\pgourlain.erlang-0.6.5\out\lib\ErlangShellDebugger.js:45:29) at ErlangDebugSession.configurationDoneRequest (c:\Users\hamba\.vscode\extensions\pgourlain.erlang-0.6.5\out\lib\erlangDebugSession.js:123:26) at ErlangDebugSession.dispatchRequest (c:\Users\hamba\.vscode\extensions\pgourlain.erlang-0.6.5\node_modules\vscode-debugadapter\lib\debugSession.js:403:22) at ErlangDebugSession.dispatchRequest (c:\Users\hamba\.vscode\extensions\pgou...
```

**Comment by pgourlain** [comment]
Fixed in v1.2.1: launching the debugger on a project that has never been `rebar3 compile`d no longer crashes with `ENOENT ... scandir '.../_build'`. See [CHANGELOG](https://github.com/pgourlain/vscode_erlang/blob/master/CHANGELOG.md#version-121-september-21-2026). Please reopen if you still see this with the latest extension version.
